version: '3'

services:
  keycloak-postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-db-network
    restart: unless-stopped
    logging:
      driver: journald
      options:
        labels: application
        tag: keycloak-postgres

  keycloak:
    image: jboss/keycloak:4.5.0.Final
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:?Please generate a secure value for KEYCLOAK_PASSWORD, using a password manager.}
      KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME:?Please configure KEYCLOAK_HOSTNAME.}
      KEYCLOAK_HTTP_PORT: 80
      KEYCLOAK_HTTPS_PORT: 443
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 8080:8080
    depends_on:
      - keycloak-postgres
    networks:
      - keycloak-db-network
    restart: unless-stopped
    logging:
      driver: journald
      options:
        labels: application
        tag: keycloak

volumes:
  keycloak-postgres-data:

networks:
  keycloak-db-network:
    driver: bridge
