name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build ./docker/glowingbear-ssl-proxy/ --file Dockerfile --tag glowingbear-ssl-proxy:$(date +%s)
