name: Docker Compose CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yml -f keycloak.yml -f glowingbear-ssl-proxy.yml -f connector.yml config 
