name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd docker/glowingbear-ssl-proxy
        docker build -t "thehyve/glowingbear-ssl-proxy:`cat version.txt`" . --no-cache
    - name: Verify tag
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        cd docker/glowingbear-ssl-proxy
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker manifest inspect "thehyve/glowingbear-ssl-proxy:`cat version.txt`"
    - name: Publish Docker image
      if: failure()
      run: |
        cd docker/glowingbear-ssl-proxy
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push "thehyve/glowingbear-ssl-proxy:`cat version.txt`"
